version: '3.8'

services:
  disco-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: disco-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - disco-backend-dev
    networks:
      - disco-network

  disco-backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: disco-backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL:-http://localhost:5000/api/auth/google/callback}
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID:-}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL:-}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY:-}
      - SESSION_SECRET=${SESSION_SECRET:-dev-session-secret}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    networks:
      - disco-network

networks:
  disco-network:
    driver: bridge
